### ISSUE TITLE
how to generate figure like this

### ISSUE THREAD

**Issue by FADHLyemen** [kstreet13/bioc2020trajectories#2]
Hi @kstreet13,
I am trying to plot a similar figure like your:
is it a umap for your cells colored by your conditions? What kind of dimensionality reduction you use.
do you have the code to produce it?
![image](https://user-images.githubusercontent.com/23288387/145324020-84e70f0e-bdfd-4c44-9e57-06024fc8ab24.png)

**Comment by kstreet13** [comment]
Hi @FADHLyemen ,

This figure is from the `condiments` paper and all the code can be found here: https://github.com/HectorRDB/condimentsPaper.

I don't know for certain what type of dimensionality reduction was used, but it is colored by condition, yes. However, this is simulated data, so whatever dimensionality reduction was used, this result is likely much cleaner than anything you would see with real data.
