### ISSUE TITLE
there is no package called ‘bioc2020trajectories’

### ISSUE THREAD

**Issue by guilingma** [kstreet13/bioc2020trajectories#5]
Hi bioc2020trajectories official,

When I am following your workshop on the trajectory analysis:

scores <- bioc2020trajectories::imbalance_score(
+     rd = reducedDims(sce)$UMAP, 
+     cl = colData(sce)$pheno$treatment_id,
+     k = 20, smooth = 40)

*_*Error in loadNamespace(x) : 
  there is no package called ‘bioc2020trajectories’**_

It says, there is no bioc2020trajectories. 

I load all the library required according your workshop instruction.

Thank you very much for your help.
Guiling

**Comment by kstreet13** [comment]
Hello @guilingma,

My guess is that this was caused by some sort of error in the package installation. What happens when you run `BiocManager::install('kstreet13/bioc2020trajectories')`?

Best,
Kelly

**Comment by guilingma** [comment]
Hi Kelly,
Thank you very much, the bioc2020trajecctoreis works now.
However, I have two questions below:

Would you like to help me again?
Thank you very much.

Qustion1:
set.seed(3)
> icMat <- evaluateK(counts = as.matrix(assays(sce)$counts),
+                    pseudotime = colData(sce)$slingshot$pseudotime,
+                    cellWeights = colData(sce)$slingshot$cellWeights.V1,
+                    conditions = factor(colData(sce)$pheno$treatment_id),
+                    nGenes = 300,
+                    k = 3:7)
Error in .local(counts, ...) :
  Either provide the slingshot object using the sds argument, or provide pseudotime and cell-level weights manually using pseudotime and cellWeights arguments.
Question 2:
When I skip the above code, and do the Fit GAM section:
It seemed the [Fit GAM] section will take ~an hour, is this normal, or there is any optional code for this section?
​
Thank you very much
Guiling Ma
________________________________

**Comment by kstreet13** [comment]
Hi @guilingma,

This is probably due the the way that `tradeSeq` handles input data from `slingshot`. The [more recent version of the workshop](https://hectorrdb.github.io/bioc2021trajectories/) may have fixed this issue, but when we changed `slingshot` to use `PseudotimeOrdering` objects, it broke some of the older code.

You should be able to get around it by substituting the appropriate accessor functions, which are always kept up-to-date. If you replace `colData(sce)$slingshot$pseudotime` with `slingPseudotime(sce)` and `colData(sce)$slingshot$cellWeights.V1,` with `slingCurveWeights(sce)`, then I think it should work.

And yes, unfortunately, this step is a little slow. It's something we're aware of, but unsure of how to fix, at the moment.

Best,
Kelly

**Comment by guilingma** [comment]
Hi Kelly,

Thank you very much for your answer.

It worked well.

Have a great day.

Guiling
________________________________
